#define UNIFORM_MARPAT_WD 0
#define UNIFORM_OCP 1
#define UNIFORM_UCP 2
#define UNIFORM_MARPAT_D 3
#define UNIFORM_G3_BLACK 4
#define UNIFORM_POLICE 5
#define UNIFORM_TTSKO_FOREST 6
#define UNIFORM_FLORA_VDV 7
#define UNIFORM_FLORA 8
#define UNIFORM_EMR_DESERT 9
#define UNIFORM_EMR_MSV 10
#define UNIFORM_TTSKO_MOUNTAIN 11
#define UNIFORM_SPECTER_S_FLORA 12
#define UNIFORM_COLDWAR_ERA_1 13
#define UNIFORM_COLDWAR_ERA_2 14
#define UNIFORM_M10_TTSKO_MOUNTAIN 15
#define UNIFORM_M10_DIGITAL 16
#define UNIFORM_M88_MOUNTAIN_LES 17
#define UNIFORM_M88_TTSKO_URBAN 18
#define UNIFORM_M93_OAKLEAF 24
#define UNIFORM_M93_FLECKTARN 19
#define UNIFORM_M93_WOODLAND 20
#define UNIFORM_GUERILLA 21
#define UNIFORM_WETSUIT 22
#define UNIFORM_CIVILIAN_TANOA 23
#define UNIFORM_CIVILIAN 25
#define WEAPONS_M16A4_M249_M240G_M136_SMAW 0
#define WEAPONS_M4A1_M249_M240G_M136_SMAW 1
#define WEAPONS_HK416D10_M249_M240G_M136_SMAW 2
#define WEAPONS_HKG36C_M249_M240G_M136_SMAW 10
#define WEAPONS_AK74M_PKM_PKP_RPG7 3
#define WEAPONS_AK74M_WOODCAMO_PKM_PKP_RPG7 4
#define WEAPONS_AKM762_PKM_PKP_RPG7 5
#define WEAPONS_MOSIN_PKM_RSHG2_RPG7 6
#define WEAPONS_KAR98K_PKM_RSHG2_RPG7 7
#define WEAPONS_UNARMED 8
#define WEAPONS_SDAR_UNDERWATER 9
#define ATTACHMENTS_NONE "";
#define ATTACHMENTS_M16_M4_HK_G36_FLASHLIGHT "rhsusf_acc_wmx";
#define ATTACHMENTS_AK_FLASHLIGHT "rhs_acc_2dpZenit";
#define ATTACHMENTS_VALUES {\
ATTACHMENTS_NONE,\
ATTACHMENTS_M16_M4_HK_G36_FLASHLIGHT,\
ATTACHMENTS_AK_FLASHLIGHT}
#define ATTACHMENTS_TEXTS {\
"No Attachments",\
"BLUFOR Flashlight (M16/M4/HK/G36)",\
"OPFOR Flashlight (AK74/AKM)"}

#define UNIFORM_VALUES {\
UNIFORM_MARPAT_WD,\
UNIFORM_OCP,\
UNIFORM_UCP,\
UNIFORM_MARPAT_D,\
UNIFORM_G3_BLACK,\
UNIFORM_POLICE,\
UNIFORM_TTSKO_FOREST,\
UNIFORM_FLORA_VDV,\
UNIFORM_EMR_DESERT,\
UNIFORM_EMR_SUMMER,\
UNIFORM_TTSKO_MOUNTAIN,\
UNIFORM_SPECTER_S_FLORA,\
UNIFORM_COLDWAR_ERA_1,\
UNIFORM_COLDWAR_ERA_2,\
UNIFORM_M10_TTSKO_MOUNTAIN,\
UNIFORM_M10_DIGITAL,\
UNIFORM_M88_MOUNTAIN_LES,\
UNIFORM_M88_TTSKO_URBAN,\
UNIFORM_M93_OAKLEAF,\
UNIFORM_M93_FLECKTARN,\
UNIFORM_M93_WOODLAND,\
UNIFORM_GUERILLA,\
UNIFORM_WETSUIT,\
UNIFORM_CIVILIAN_TANOA,\
UNIFORM_CIVILIAN}
#define UNIFORM_TEXTS {\
"B MARPAT WD*",\
"B OCP*",\
"B UCP*",\
"B MARPAT D*",\
"B G3 Black~",\
"B Police~",\
"O TTsKO Forest~",\
"O Flora VDV*",\
"O EMR Desert*",\
"O EMR Summer*",\
"O TTsKO Mountain~",\
"I Specter-S Flora~",\
"I Cold War Era 1~",\
"I Cold War Era 2~",\
"O M10 TTsKO Mountain*",\
"O M10 Digital*",\
"O M88 Mountain Les*",\
"O M88 TTsKO Urban~",\
"O M93 Oakleaf~",\
"I M93 Flecktarn~",\
"I M93 Woodland~",\
"I Guerilla~",\
"B Wetsuit~",\
"C Civilian (Tanoa)",\
"C Civilian"}

#define WEAPON_VALUES {\
WEAPONS_M16A4_M249_M240G_M136_SMAW,\
WEAPONS_M4A1_M249_M240G_M136_SMAW,\
WEAPONS_HK416D10_M249_M240G_M136_SMAW,\
WEAPONS_HKG36C_M249_M240G_M136_SMAW,\
WEAPONS_AK74M_PKM_PKP_RPG7,\
WEAPONS_AK74M_WOODCAMO_PKM_PKP_RPG7,\
WEAPONS_AKM762_PKM_PKP_RPG7,\
WEAPONS_MOSIN_PKM_RSHG2_RPG7,\
WEAPONS_KAR98K_PKM_RSHG2_RPG7,\
WEAPONS_UNARMED,\
WEAPONS_SDAR_UNDERWATER}

#define WEAPON_TEXTS {\
"B M16A4, M249, M240G, M136 / SMAW",\
"B M4A1, M249, M240G, M136 / SMAW",\
"B HK416 D10, M249, M240G, M136 / SMAW",\
"B HK G36C, M249, M240G, M136 / SMAW",\
"O AK74M, PKM, PKP, RPG7",\
"O AK74M (Wood Camo), PKM, PKP, RPG7",\
"O AKM (7.62), PKM, PKP, RPG7",\
"I Mosin, PKM, RShG-2 / RPG7",\
"I Kar98k, PKM, RShG-2 / RPG7",\
"Unarmed",\
"SDAR Underwater"}

#define ROLE_SPECTATOR 99
#define ROLE_PL 0
#define ROLE_CLS 1
#define ROLE_SL 2
#define ROLE_TL 3
#define ROLE_AR 4
#define ROLE_AAR 5
#define ROLE_RAT 6
#define ROLE_CE 7
#define ROLE_R 8
#define ROLE_MG 9
#define ROLE_AM 10
#define ROLE_MGTL 11
#define ROLE_AT 12
#define ROLE_AAT 13
#define ROLE_P 14
#define ROLE_CR 15
#define ROLE_MK 16

#define UNIT_SPECTATOR "VirtualMan_F"

#define UNIT_OPFOR_PL "O_officer_F"
#define UNIT_OPFOR_CLS "O_medic_F"
#define UNIT_OPFOR_SL "O_Soldier_SL_F"
#define UNIT_OPFOR_TL "O_Soldier_TL_F"
#define UNIT_OPFOR_AR "O_Soldier_AR_F"
#define UNIT_OPFOR_AAR "O_Soldier_A_F"
#define UNIT_OPFOR_RAT "O_Soldier_LAT_F"
#define UNIT_OPFOR_CE "O_soldier_exp_F"
#define UNIT_OPFOR_R "O_Soldier_F"
#define UNIT_OPFOR_MG "O_HeavyGunner_F"
#define UNIT_OPFOR_AM "O_Soldier_unarmed_F"
#define UNIT_OPFOR_MGTL "O_soldier_PG_F"
#define UNIT_OPFOR_AT "O_Soldier_AT_F"
#define UNIT_OPFOR_AAT "O_Soldier_AAT_F"
#define UNIT_OPFOR_P "O_pilot_F"
#define UNIT_OPFOR_CR ""
#define UNIT_OPFOR_MK ""

#define UNIT_BLUFOR_PL "B_officer_F"
#define UNIT_BLUFOR_CLS "B_medic_F"
#define UNIT_BLUFOR_SL "B_Soldier_SL_F"
#define UNIT_BLUFOR_TL "B_Soldier_TL_F"
#define UNIT_BLUFOR_AR "B_soldier_AR_F"
#define UNIT_BLUFOR_AAR "B_soldier_AAR_F"
#define UNIT_BLUFOR_RAT "B_soldier_LAT_F"
#define UNIT_BLUFOR_CE "B_soldier_exp_F"
#define UNIT_BLUFOR_R "B_Soldier_F"
#define UNIT_BLUFOR_MG "B_HeavyGunner_F"
#define UNIT_BLUFOR_AM "B_Soldier_unarmed_F"
#define UNIT_BLUFOR_MGTL "B_soldier_PG_F"
#define UNIT_BLUFOR_AT "B_Soldier_AT_F"
#define UNIT_BLUFOR_AAT "B_Soldier_AAT_F"
#define UNIT_BLUFOR_P "B_pilot_F"
#define UNIT_BLUFOR_CR ""
#define UNIT_BLUFOR_MK ""

#define UNIT_INDFOR_PL "I_officer_F"
#define UNIT_INDFOR_CLS "I_medic_F"
#define UNIT_INDFOR_SL "I_Soldier_SL_F"
#define UNIT_INDFOR_TL "I_Soldier_TL_F"
#define UNIT_INDFOR_AR "I_Soldier_AR_F"
#define UNIT_INDFOR_AAR "I_Soldier_AAR_F"
#define UNIT_INDFOR_RAT "I_Soldier_LAT_F"
#define UNIT_INDFOR_CE "I_engineer_F"
#define UNIT_INDFOR_R "I_soldier_F"
#define UNIT_INDFOR_MG "I_support_MG_F"
#define UNIT_INDFOR_AM "I_Soldier_A_F"
#define UNIT_INDFOR_MGTL "I_Soldier_lite_F"
#define UNIT_INDFOR_AT "I_Soldier_AT_F"
#define UNIT_INDFOR_AAT "I_Soldier_AAT_F"
#define UNIT_INDFOR_P "I_pilot_F"
#define UNIT_INDFOR_CR ""
#define UNIT_INDFOR_MK ""

#define UNIT_CIV_R "C_man_1_1_F"
